import type { BestCreatorCursorListTypes2 } from "@/types/best/bestTypes"

export const dummyRankingData: BestCreatorCursorListTypes2 = {
	content: [
		{
			memberUuid: "member-1",
			ranking: 1,
			rankingChange: 5,
			dailySellsCount: 30,
			reviewAvg: 4.5,
			date: "2024-12-08",
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/profile/TestAvartar.png",
			nickname: "Creator-1",
			follower: 5000,
			hashTag: "#Tag1",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-2",
			ranking: 2,
			rankingChange: -3,
			dailySellsCount: 45,
			reviewAvg: 3.8,
			date: "2024-12-08",
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			nickname: "Creator-2",
			follower: 4300,
			hashTag: undefined,
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-3",
			ranking: 3,
			rankingChange: 0,
			dailySellsCount: 20,
			reviewAvg: 4.0,
			date: "2024-12-08",
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/profile/TestAvartar.png",
			nickname: "Creator-3",
			follower: 6200,
			hashTag: "#Tag3",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-4",
			ranking: 4,
			rankingChange: 2,
			dailySellsCount: 15,
			reviewAvg: 3.5,
			date: "2024-12-08",
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			nickname: "Creator-4",
			follower: 3000,
			hashTag: undefined,
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-5",
			ranking: 5,
			rankingChange: -1,
			dailySellsCount: 25,
			reviewAvg: 4.2,
			date: "2024-12-08",
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/profile/TestAvartar.png",
			nickname: "Creator-5",
			follower: 7100,
			hashTag: "#Tag5",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-6",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-7",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-8",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-9",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-10",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-11",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-12",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-13",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-14",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-15",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-16",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-17",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-18",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-19",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-20",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-21",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
		{
			memberUuid: "member-22",
			ranking: 6,
			avatarImage:
				"https://promptoven.s3.ap-northeast-2.amazonaws.com/dummy/prompt-detail/PromptDetailThumbnail.png",
			date: "2024-12-08",
			reviewAvg: 3.9,
			dailySellsCount: 10,
			rankingChange: 1,
			nickname: "Creator-6",
			follower: 4000,
			hashTag: "#Tag6",
			totalSales: 0,
			views: 0,
		},
	],
	nextCursor: 2,
	hasNext: true,
	pageSize: 20,
	page: 1,
}

