name: Continuous Integration

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ matrix.node-version }}-${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.node-version }}-${{ runner.os }}-pnpm-store-
            
      - name: Cache Next.js and Turbo
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/apps/client/.next/cache
            ${{ github.workspace }}/apps/admin/.next/cache
            .turbo
          key: ${{ runner.os }}-nextjs-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nextjs-turbo-
              
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: make .env file
        run: |
          echo "${{ secrets.FE_CLIENT_ENV }}" > ${{ github.workspace }}/apps/client/.env
          echo "${{ secrets.FE_ADMIN_ENV }}" > ${{ github.workspace }}/apps/admin/.env
      
      - name: Build applications
        run: pnpm turbo build 
